const errorTypes = {
  DUPLICATED_ENTITY: 'DUPLICATED_ENTITY',
  DEFAULT_ERROR: 'DEFAULT_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  FORBIDDEN: 'FORBIDDEN',
}

module.exports = errorTypes
