stages:
  - deploy

deploy_to_prod:
  stage: deploy
  tags:
    - node
  script:
    - cd /home/admin2/preregovorki-inernship-be
    - git pull origin $CI_COMMIT_REF_NAME
    - make down
    - make prod
  when: manual
  only:
    - master

variables:
  GIT_SSL_NO_VERIFY: "true"
